### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by AdamFeit** [enzo-g/MP-SMS#1]
I am having trouble setting this addon. Link to your instructions do not work, you can upload it somewhere else?

Thanks a lot my friend
Adam ;)

**Comment by enzo-g** [comment]
Hi ! Sorry, I forgot to answer, unfortunately I closed "by accident" few days ago...
Anyway, I just realized that the instruction was in french. I have to rewrite it in english. I will do it soon ! (probably this weekend) thanks for your interest.

**Comment by enzo-g** [comment]
In few minutes a backup of the webpage you wanted to read... still in French.

**Comment by AdamFeit** [comment]
Bonjour, la langue française ne me dérange pas, je ai travaillé à Paris, 
donc je parle un peu le français;)

Adam

Dne 27.2.2015 v 1:21 enzo-g napsal(a):
> Hi ! Sorry, I forgot to answer, unfortunately I closed "by accident" 
> few days ago...
> Anyway, I just realized that the instruction was in french. I have to 
> rewrite it in english. I will do it soon ! (probably this weekend) 
> thanks for your interest.


---
Tato zpráva byla zkontrolována na viry programem Avast Antivirus.
http://www.avast.com

**Comment by AdamFeit** [comment]
Hi Enzo, you somehow progressed with the manual?

**Comment by enzo-g** [comment]
Hi, sorry, I forgot to commit ^^
Look after this file: "Un add-on SMS à MailPoet - Linked.mht" is an extraction from dead website, where I posted the explanation on how to install and deploy this plugin. I hope it will be enought. :)

**Comment by AdamFeit** [comment]
Hello, unfortunately, when it opens in the browser so I can only see garbage characters

**Comment by enzo-g** [comment]
Download all the files as a zip, open the .mht file with firefox (it's an advice), eventually install unmht extension. :)

**Comment by AdamFeit** [comment]
Super, now is working ;) You are the Boss ;) Thanks
